# Generated by Django 6.0 on 2025-12-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("course", models.CharField(max_length=100)),
            ],
        ),
    ]
