# Generated by Django 6.0 on 2025-12-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="id",
            new_name="student_id",
        ),
    ]
