# Generated by Django 6.0 on 2025-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_rename_id_student_student_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.AddField(
            model_name="student",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
